# Generated by Django 6.0.3 on 2026-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_contact_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="contact_files/"),
        ),
    ]
